name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run Jest unit tests
      - name: Run unit tests
        run: npm test -- --ci --reporters=default --reporters=jest-junit

      # 5. Start the Vite dev server in the background
      - name: Start Vite server
        run: npm run dev &
      
      # 6. Wait for the server to be ready
      - name: Wait for server
        run: npx wait-on http://localhost:5173

      # 7. Run Cypress E2E tests
      - name: Run Cypress tests
        run: npx cypress run
